// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Start up the program, login, insert a patient.
        /// </summary>
        public void TestpatientInsert()
        {
            #region Variable Declarations
            WpfEdit uIItemEdit = this.UILoginWindow.UIItemEdit;
            WpfEdit uIItemEdit1 = this.UILoginWindow.UIItemEdit1;
            WpfButton uILoginButton = this.UILoginWindow.UILoginButton;
            WpfTabPage uIPatientsTabPage = this.UIMainWindowWindow.UIItemTabList.UIPatientsTabPage;
            WpfButton uICreateNewPatientButton = this.UIMainWindowWindow.UIItemTabList.UIPatientsTabPage.UICreateNewPatientButton;
            WpfEdit uIItemEdit2 = this.UICreateNewPatientWindow.UIItemEdit;
            WpfComboBox uIGenderComboBox = this.UICreateNewPatientWindow.UIGenderComboBox;
            WpfComboBox uIAgeGroupComboBox = this.UICreateNewPatientWindow.UIAgeGroupComboBox;
            WpfEdit uIItemEdit11 = this.UICreateNewPatientWindow.UIItemEdit1;
            WpfEdit uIItemEdit21 = this.UICreateNewPatientWindow.UIItemEdit2;
            WpfWindow uICreateNewPatientWindow = this.UICreateNewPatientWindow;
            WpfComboBox uIEthnicityComboBox = this.UICreateNewPatientWindow.UIEthnicityComboBox;
            WpfEdit uIItemEdit3 = this.UICreateNewPatientWindow.UIItemEdit3;
            WpfCheckBox uIIsHeadofHouseholdCheckBox = this.UICreateNewPatientWindow.UIIsHeadofHouseholdCheckBox;
            WpfCheckBox uIFirstMemberofHousehoCheckBox = this.UICreateNewPatientWindow.UIFirstMemberofHousehoCheckBox;
            WpfButton uIAddClientButton = this.UICreateNewPatientWindow.UIAddClientButton;
            WpfEdit uIItemEdit4 = this.UICreateHouseholdWindow.UIItemEdit;
            WpfEdit uIItemEdit12 = this.UICreateHouseholdWindow.UIItemEdit1;
            WpfComboBox uIIncomeComboBox = this.UICreateHouseholdWindow.UIIncomeComboBox;
            WpfButton uIAddHouseholdButton = this.UICreateHouseholdWindow.UIAddHouseholdButton;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WpfButton uIRefreshButton = this.UIMainWindowWindow.UIItemTabList.UIPatientsTabPage.UIRefreshButton;
            #endregion

            // Launch '%ProgramFiles%\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\ScriptedSandbox64.exe' with arguments '"Software\Microsoft\VisualStudio\14.0\ScriptedPlugins" "Software\Microsoft\VisualStudio\14.0_Config\ScriptedPlugins" d0352 2b98 "file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/plugin.vs.js"'
            ApplicationUnderTest scriptedSandbox64Application = ApplicationUnderTest.Launch(this.TestpatientInsertParams.ExePath, this.TestpatientInsertParams.AlternateExePath, "\"Software\\Microsoft\\VisualStudio\\14.0\\ScriptedPlugins\" \"Software\\Microsoft\\Visual" +
                    "Studio\\14.0_Config\\ScriptedPlugins\" d0352 2b98 \"file:///C:/Program Files (x86)/M" +
                    "icrosoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/plugin.vs.js\"");

            // Element not available

            // Type 'username' in text box
            uIItemEdit.Text = this.TestpatientInsertParams.UIItemEditText;

            // Click text box numbered 2 in 'Login' window
            Mouse.Click(uIItemEdit1, new Point(59, 21));

            // Type '********' in text box numbered 2 in 'Login' window
            Keyboard.SendKeys(uIItemEdit1, this.TestpatientInsertParams.UIItemEdit1SendKeys, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(32, 34));

            // Click 'Patients' tab
            Mouse.Click(uIPatientsTabPage, new Point(136, 45));

            // Click 'Create New Patient' button
            Mouse.Click(uICreateNewPatientButton, new Point(138, 36));

            // Type '55' in text box
            uIItemEdit2.Text = this.TestpatientInsertParams.UIItemEditText1;

            // Select 'Other' in 'Gender' combo box
            uIGenderComboBox.SelectedItem = this.TestpatientInsertParams.UIGenderComboBoxSelectedItem;

            // Select '24-44' in 'AgeGroup' combo box
            uIAgeGroupComboBox.SelectedItem = this.TestpatientInsertParams.UIAgeGroupComboBoxSelectedItem;

            // Type 'Kenneth' in text box numbered 2 in 'CreateNewPatient' window
            uIItemEdit11.Text = this.TestpatientInsertParams.UIItemEdit1Text;

            // Type 'Adair' in text box numbered 3 in 'CreateNewPatient' window
            uIItemEdit21.Text = this.TestpatientInsertParams.UIItemEdit2Text;

            // Move text box numbered 3 in 'CreateNewPatient' window to 'CreateNewPatient' window
            uICreateNewPatientWindow.EnsureClickable(new Point(469, 462));
            Mouse.StartDragging(uIItemEdit21, new Point(137, 27));
            Mouse.StopDragging(uICreateNewPatientWindow, new Point(469, 462));

            // Select 'Hispanic' in 'ethnicity' combo box
            uIEthnicityComboBox.SelectedItem = this.TestpatientInsertParams.UIEthnicityComboBoxSelectedItem;

            // Type 'Kid' in text box numbered 4 in 'CreateNewPatient' window
            uIItemEdit3.Text = this.TestpatientInsertParams.UIItemEdit3Text;

            // Select 'Is Head of Household?' check box
            uIIsHeadofHouseholdCheckBox.Checked = this.TestpatientInsertParams.UIIsHeadofHouseholdCheckBoxChecked;

            // Select 'First Member of Household?' check box
            uIFirstMemberofHousehoCheckBox.Checked = this.TestpatientInsertParams.UIFirstMemberofHousehoCheckBoxChecked;

            // Click 'Add Client' button
            Mouse.Click(uIAddClientButton, new Point(112, 33));

            // Type '5' in text box
            uIItemEdit4.Text = this.TestpatientInsertParams.UIItemEditText2;

            // Type 'Davis' in text box numbered 2 in 'CreateHousehold' window
            uIItemEdit12.Text = this.TestpatientInsertParams.UIItemEdit1Text1;

            // Select '$35,000+' in 'income' combo box
            uIIncomeComboBox.SelectedItem = this.TestpatientInsertParams.UIIncomeComboBoxSelectedItem;

            // Click 'Add Household' button
            Mouse.Click(uIAddHouseholdButton, new Point(165, 35));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(35, 22));

            // Click 'Refresh' button
            Mouse.Click(uIRefreshButton, new Point(94, 48));

            // The control is not available or not valid.

            // Last action on Row was not recorded because the control does not have any good identification property.

            // Last action on Row was not recorded because the control does not have any good identification property.
        }
        
        #region Properties
        public virtual TestpatientInsertParams TestpatientInsertParams
        {
            get
            {
                if ((this.mTestpatientInsertParams == null))
                {
                    this.mTestpatientInsertParams = new TestpatientInsertParams();
                }
                return this.mTestpatientInsertParams;
            }
        }
        
        public UILoginWindow UILoginWindow
        {
            get
            {
                if ((this.mUILoginWindow == null))
                {
                    this.mUILoginWindow = new UILoginWindow();
                }
                return this.mUILoginWindow;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UICreateNewPatientWindow UICreateNewPatientWindow
        {
            get
            {
                if ((this.mUICreateNewPatientWindow == null))
                {
                    this.mUICreateNewPatientWindow = new UICreateNewPatientWindow();
                }
                return this.mUICreateNewPatientWindow;
            }
        }
        
        public UICreateHouseholdWindow UICreateHouseholdWindow
        {
            get
            {
                if ((this.mUICreateHouseholdWindow == null))
                {
                    this.mUICreateHouseholdWindow = new UICreateHouseholdWindow();
                }
                return this.mUICreateHouseholdWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private TestpatientInsertParams mTestpatientInsertParams;
        
        private UILoginWindow mUILoginWindow;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UICreateNewPatientWindow mUICreateNewPatientWindow;
        
        private UICreateHouseholdWindow mUICreateHouseholdWindow;
        
        private UIOKWindow mUIOKWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestpatientInsert'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestpatientInsertParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles%\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\ScriptedSandbox64.exe' with arguments '"Software\Microsoft\VisualStudio\14.0\ScriptedPlugins" "Software\Microsoft\VisualStudio\14.0_Config\ScriptedPlugins" d0352 2b98 "file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/plugin.vs.js"'
        /// </summary>
        public string ExePath = "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\PrivateAssemblies" +
            "\\ScriptedSandbox64.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles%\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\ScriptedSandbox64.exe' with arguments '"Software\Microsoft\VisualStudio\14.0\ScriptedPlugins" "Software\Microsoft\VisualStudio\14.0_Config\ScriptedPlugins" d0352 2b98 "file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/plugin.vs.js"'
        /// </summary>
        public string AlternateExePath = "%ProgramFiles%\\Microsoft Visual Studio 14.0\\Common7\\IDE\\PrivateAssemblies\\Scripte" +
            "dSandbox64.exe";
        
        /// <summary>
        /// Type 'username' in text box
        /// </summary>
        public string UIItemEditText = "username";
        
        /// <summary>
        /// Type '********' in text box numbered 2 in 'Login' window
        /// </summary>
        public string UIItemEdit1SendKeys = "QWwOodIXpSM441BCNCWNvH9k+8fhegdI";
        
        /// <summary>
        /// Type '55' in text box
        /// </summary>
        public string UIItemEditText1 = "55";
        
        /// <summary>
        /// Select 'Other' in 'Gender' combo box
        /// </summary>
        public string UIGenderComboBoxSelectedItem = "Other";
        
        /// <summary>
        /// Select '24-44' in 'AgeGroup' combo box
        /// </summary>
        public string UIAgeGroupComboBoxSelectedItem = "24-44";
        
        /// <summary>
        /// Type 'Kenneth' in text box numbered 2 in 'CreateNewPatient' window
        /// </summary>
        public string UIItemEdit1Text = "Kenneth";
        
        /// <summary>
        /// Type 'Adair' in text box numbered 3 in 'CreateNewPatient' window
        /// </summary>
        public string UIItemEdit2Text = "Adair";
        
        /// <summary>
        /// Select 'Hispanic' in 'ethnicity' combo box
        /// </summary>
        public string UIEthnicityComboBoxSelectedItem = "Hispanic";
        
        /// <summary>
        /// Type 'Kid' in text box numbered 4 in 'CreateNewPatient' window
        /// </summary>
        public string UIItemEdit3Text = "Kid";
        
        /// <summary>
        /// Select 'Is Head of Household?' check box
        /// </summary>
        public bool UIIsHeadofHouseholdCheckBoxChecked = true;
        
        /// <summary>
        /// Select 'First Member of Household?' check box
        /// </summary>
        public bool UIFirstMemberofHousehoCheckBoxChecked = true;
        
        /// <summary>
        /// Type '5' in text box
        /// </summary>
        public string UIItemEditText2 = "5";
        
        /// <summary>
        /// Type 'Davis' in text box numbered 2 in 'CreateHousehold' window
        /// </summary>
        public string UIItemEdit1Text1 = "Davis";
        
        /// <summary>
        /// Select '$35,000+' in 'income' combo box
        /// </summary>
        public string UIIncomeComboBoxSelectedItem = "$35,000+";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginWindow : WpfWindow
    {
        
        public UILoginWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Login";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Login");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Login");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WpfEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.SearchProperties[WpfEdit.PropertyNames.Instance] = "2";
                    this.mUIItemEdit1.WindowTitles.Add("Login");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        
        public WpfButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WpfButton.PropertyNames.Name] = "Login";
                    this.mUILoginButton.WindowTitles.Add("Login");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        
        private WpfEdit mUIItemEdit1;
        
        private WpfButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTabList mUIItemTabList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTabList : WpfTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIPatientsTabPage UIPatientsTabPage
        {
            get
            {
                if ((this.mUIPatientsTabPage == null))
                {
                    this.mUIPatientsTabPage = new UIPatientsTabPage(this);
                }
                return this.mUIPatientsTabPage;
            }
        }
        #endregion
        
        #region Fields
        private UIPatientsTabPage mUIPatientsTabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPatientsTabPage : WpfTabPage
    {
        
        public UIPatientsTabPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTabPage.PropertyNames.Name] = "Patients";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UICreateNewPatientButton
        {
            get
            {
                if ((this.mUICreateNewPatientButton == null))
                {
                    this.mUICreateNewPatientButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICreateNewPatientButton.SearchProperties[WpfButton.PropertyNames.Name] = "Create New Patient";
                    this.mUICreateNewPatientButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICreateNewPatientButton;
            }
        }
        
        public WpfButton UIRefreshButton
        {
            get
            {
                if ((this.mUIRefreshButton == null))
                {
                    this.mUIRefreshButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIRefreshButton.SearchProperties[WpfButton.PropertyNames.Name] = "Refresh";
                    this.mUIRefreshButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIRefreshButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICreateNewPatientButton;
        
        private WpfButton mUIRefreshButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateNewPatientWindow : WpfWindow
    {
        
        public UICreateNewPatientWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "CreateNewPatient";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("CreateNewPatient");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WpfComboBox UIGenderComboBox
        {
            get
            {
                if ((this.mUIGenderComboBox == null))
                {
                    this.mUIGenderComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIGenderComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "Gender";
                    this.mUIGenderComboBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIGenderComboBox;
            }
        }
        
        public WpfComboBox UIAgeGroupComboBox
        {
            get
            {
                if ((this.mUIAgeGroupComboBox == null))
                {
                    this.mUIAgeGroupComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIAgeGroupComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "AgeGroup";
                    this.mUIAgeGroupComboBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIAgeGroupComboBox;
            }
        }
        
        public WpfEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.SearchProperties[WpfEdit.PropertyNames.Instance] = "2";
                    this.mUIItemEdit1.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        
        public WpfEdit UIItemEdit2
        {
            get
            {
                if ((this.mUIItemEdit2 == null))
                {
                    this.mUIItemEdit2 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit2.SearchProperties[WpfEdit.PropertyNames.Instance] = "3";
                    this.mUIItemEdit2.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIItemEdit2;
            }
        }
        
        public WpfComboBox UIEthnicityComboBox
        {
            get
            {
                if ((this.mUIEthnicityComboBox == null))
                {
                    this.mUIEthnicityComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIEthnicityComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "ethnicity";
                    this.mUIEthnicityComboBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIEthnicityComboBox;
            }
        }
        
        public WpfEdit UIItemEdit3
        {
            get
            {
                if ((this.mUIItemEdit3 == null))
                {
                    this.mUIItemEdit3 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit3.SearchProperties[WpfEdit.PropertyNames.Instance] = "4";
                    this.mUIItemEdit3.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIItemEdit3;
            }
        }
        
        public WpfCheckBox UIIsHeadofHouseholdCheckBox
        {
            get
            {
                if ((this.mUIIsHeadofHouseholdCheckBox == null))
                {
                    this.mUIIsHeadofHouseholdCheckBox = new WpfCheckBox(this);
                    #region Search Criteria
                    this.mUIIsHeadofHouseholdCheckBox.SearchProperties[WpfCheckBox.PropertyNames.Name] = "Is Head of Household?";
                    this.mUIIsHeadofHouseholdCheckBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIIsHeadofHouseholdCheckBox;
            }
        }
        
        public WpfCheckBox UIFirstMemberofHousehoCheckBox
        {
            get
            {
                if ((this.mUIFirstMemberofHousehoCheckBox == null))
                {
                    this.mUIFirstMemberofHousehoCheckBox = new WpfCheckBox(this);
                    #region Search Criteria
                    this.mUIFirstMemberofHousehoCheckBox.SearchProperties[WpfCheckBox.PropertyNames.Name] = "First Member of Household?";
                    this.mUIFirstMemberofHousehoCheckBox.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIFirstMemberofHousehoCheckBox;
            }
        }
        
        public WpfButton UIAddClientButton
        {
            get
            {
                if ((this.mUIAddClientButton == null))
                {
                    this.mUIAddClientButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAddClientButton.SearchProperties[WpfButton.PropertyNames.Name] = "Add Client";
                    this.mUIAddClientButton.WindowTitles.Add("CreateNewPatient");
                    #endregion
                }
                return this.mUIAddClientButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        
        private WpfComboBox mUIGenderComboBox;
        
        private WpfComboBox mUIAgeGroupComboBox;
        
        private WpfEdit mUIItemEdit1;
        
        private WpfEdit mUIItemEdit2;
        
        private WpfComboBox mUIEthnicityComboBox;
        
        private WpfEdit mUIItemEdit3;
        
        private WpfCheckBox mUIIsHeadofHouseholdCheckBox;
        
        private WpfCheckBox mUIFirstMemberofHousehoCheckBox;
        
        private WpfButton mUIAddClientButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateHouseholdWindow : WpfWindow
    {
        
        public UICreateHouseholdWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "CreateHousehold";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("CreateHousehold");
            #endregion
        }
        
        #region Properties
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("CreateHousehold");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WpfEdit UIItemEdit1
        {
            get
            {
                if ((this.mUIItemEdit1 == null))
                {
                    this.mUIItemEdit1 = new WpfEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit1.SearchProperties[WpfEdit.PropertyNames.Instance] = "2";
                    this.mUIItemEdit1.WindowTitles.Add("CreateHousehold");
                    #endregion
                }
                return this.mUIItemEdit1;
            }
        }
        
        public WpfComboBox UIIncomeComboBox
        {
            get
            {
                if ((this.mUIIncomeComboBox == null))
                {
                    this.mUIIncomeComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIIncomeComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "income";
                    this.mUIIncomeComboBox.WindowTitles.Add("CreateHousehold");
                    #endregion
                }
                return this.mUIIncomeComboBox;
            }
        }
        
        public WpfButton UIAddHouseholdButton
        {
            get
            {
                if ((this.mUIAddHouseholdButton == null))
                {
                    this.mUIAddHouseholdButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAddHouseholdButton.SearchProperties[WpfButton.PropertyNames.Name] = "Add Household";
                    this.mUIAddHouseholdButton.WindowTitles.Add("CreateHousehold");
                    #endregion
                }
                return this.mUIAddHouseholdButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUIItemEdit;
        
        private WpfEdit mUIItemEdit1;
        
        private WpfComboBox mUIIncomeComboBox;
        
        private WpfButton mUIAddHouseholdButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
